batch_size: 256
clip_gradient_norm: 1
commit_hash: f798676
data_dir: # path to CAMGEN
dataset: generic
device: cpu
dynamic_inputs:
- prcp(mmperday)_daymet
- srad(Wperm2)_daymet
- tmax(C)_daymet
- tmin(C)_daymet
- vp(Pa)_daymet
- PRCP(mmperday)_nldas
- SRAD(Wperm2)_nldas
- Tmax(C)_nldas
- Tmin(C)_nldas
- Vp(Pa)_nldas
- PRCP(mmperday)_maurer
- SRAD(Wperm2)_maurer
- Tmax(C)_maurer
- Tmin(C)_maurer
- Vp(Pa)_maurer
epochs: 30
experiment_name: 531_basins_multi_forcings_generic
forcings:
- daymet
- maurer
- nldas
head: regression
hidden_size: 256
img_log_dir: img_log
initial_forget_bias: 3
learning_rate:
  0: 0.001
  20: 0.0005
  25: 0.0001
log_interval: 5
log_tensorboard: true
loss: NSE
metrics:
- NSE
- KGE
- Pearson-r
- Alpha-NSE
- Beta-NSE
- Beta-KGE
- Peak-Timing
- Missed-Peaks
model: cudalstm
num_workers: 8
number_of_basins: 531
optimizer: Adam
output_activation: linear
output_dropout: 0.4
package_version: 1.9.0
predict_last_n: 1
run_dir: # probably CAMGEN/nh_model
save_validation_results: true
save_weights_every: 1
seed: 473461
seq_length: 365
static_attributes:
- elev_mean
- slope_mean
- area_gages2
- frac_forest
- lai_max
- lai_diff
- gvf_max
- gvf_diff
- soil_depth_pelletier
- soil_depth_statsgo
- soil_porosity
- soil_conductivity
- max_water_content
- sand_frac
- silt_frac
- clay_frac
- carbonate_rocks_frac
- geol_permeability
- p_mean
- pet_mean
- aridity
- frac_snow
- high_prec_freq
- high_prec_dur
- low_prec_freq
- low_prec_dur
target_variables:
- QObs(mmperd)
test_basin_file: # probably CAMGEN/basin_list.txt
test_end_date: 30/09/1999
test_start_date: 01/10/1989
train_basin_file: # probably CAMGEN/basin_list.txt
train_dir: # probably CAMGEN/nh_model/train_data
train_end_date: 30/09/2008
train_start_date: 01/10/1999
validate_every: 1
validate_n_random_basins: 531
validation_basin_file: # probably CAMGEN/basin_list.txt
validation_end_date: 30/09/1989
validation_start_date: 01/10/1980